# Dockerfile for the Product API
# Complete the TODOs below to containerize this Fastify application

FROM oven/bun:latest

WORKDIR /app

# TODO 1: Copy the dependency files (package.json and bun.lock)


# TODO 2: Install dependencies (hint: bun install --frozen-lockfile)


# TODO 3: Copy the application source code (src/ directory)


# TODO 4: Expose the port the application runs on


# TODO 5: Set the command to start the Fastify server
# (hint: the app entry point is src/api/app.ts)

